version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_red_devils_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - api_red_devils_network
    depends_on:
      - mysql
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: api_red_devils_nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - api_red_devils_network
    depends_on:
      - app
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: api_red_devils_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: 1234
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - api_red_devils_network
    restart: unless-stopped

volumes:
  dbdata:

networks:
  api_red_devils_network:
    driver: bridge
